version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - data-postgres:/var/lib/postgres/data

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "financial_control@example.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
    ports:
      - "16543:80"
    depends_on:
      - db

volumes:
  data-postgres: